cancer:
  question: "What are the tissue sources that are investigated in this report? Is there cancer diagnosed in this report?\nOnly include tissue sources in the output if they are investigated. Please output the cancer diagnosis in json format: {\"Cancer_Diagnosis\": {\"Right Breast\": __, \"Left Breast\": __}}, where each blank is filled in by \"1\" if any cancer is diagnosed and \"0\" if the tissue is benign. If neither breast is investigated, output {\"Cancer_Diagnosis\":{}}.\nProvide your answer in the required format. Do not provide explanations or output anything else."
  gt_columns: ["Cancer_Diagnosis"]
  parse_response: "parse_functions/example/default.py"
  preamble: "You are an experienced pathologist. Answer the question using the pathology report below. Base the answer on the report only. Do not add any additional information."
  response_start: "My answer is:"
  question_name: "Findings"

